eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: requestratelimiter_route
        uri: http://www.baidu.com
        order: 10000
        predicates:
        - Path=/baidu/**
        filters:
        - name: RequestRateLimiter
          args:
            #            rate-limiter: "#{@myRateLimiter}" #使用自定义
            redis-rate-limiter.replenishRate: 1  # 流速 每秒
            redis-rate-limiter.burstCapacity: 1  # 容量
            key-resolver: "#{@myKeyResolver}" #SPEL表达式去的对应的bean
        - StripPrefix=1



