#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/
spring:
  application:
    name: gateway
#  http:
#    multipart:
#      max-file-size: 10Mb      # Max file size，默认1M
#      max-request-size: 20Mb   # Max request size，默认10M
#      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
#      location: /  # 上传的临时目录

server:
  port: 8080
zuul:
  routes:
#    service-user:
#      sensitive-headers: Cookie,Set-Cookie
#      ignored-headers: Authorization
#      path: /user/**
#      serviceId: service-user
#    service-monitoring: /monitoring/**
    file-api:
      path: /uploadFile/**
      url: http://127.0.0.1:8081