eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
spring:
  application:
    name: gateway
server:
  port: 8080
zuul:
  routes:
    service-user: /user/**
    service-monitoring: /monitoring/**